---
- name: Install containerd
  hosts: all
  become: true
  roles:
  - { role: containerd, tags: containerd }

- name: Install Kubernetes packages
  hosts: all
  become: yes
  roles:
  - { role: k8s, tags: k8s }


- name: Deploy master for kubeadm
  hosts: k8s-master
  become: true
  roles:
  - { role: master, tags: master }

- name: Deploy additional master for kubeadm
  hosts: k8s-additional-masters
  become: true
  roles:
  - { role: additional-master, tags: additional-master }

- name: Deploy workers for kubeadm
  hosts: k8s-workers
  become: true
  roles:
  - { role: worker, tags: worker }

- name: Deploy metallb on master nodes
  hosts: k8s-master
  become: true
  roles:
  - { role: metallb, tags: metallb }