---
- name: Install Docker
  hosts: all
  become: true
  roles:
  - { role: docker, tags: docker }

- name: Install cri-dockerd
  hosts: all
  become: yes
  roles:
  - { role: cri-dockerd, tags: cri-dockerd }

- name: Install Kubernetes packages
  hosts: all
  become: yes
  roles:
  - { role: k8s, tags: k8s }


- name: Deploy master for kubeadm
  hosts: k8s-master
  become: true
  roles:
  - { role: master, tags: master }

- name: Deploy additional master for kubeadm
  hosts: k8s-additional-masters
  become: true
  roles:
  - { role: additional-master, tags: additional-master }

- name: Deploy workers for kubeadm
  hosts: k8s-workers
  become: true
  roles:
  - { role: worker, tags: worker }
