---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - socat
    state: present

- name: Install NFS client dependencies (autofs, nfs-common)
  apt:
    name:
      - autofs
      - nfs-common
    state: present
  when: k8s_csi_plugin == 'nfs'

- name: Ensure directory for apt keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download the Kubernetes apt keyring
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes-apt-keyring.key
    mode: '0644'

- name: De-armor the Kubernetes apt keyring
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg # Only run if the final file doesn't exist

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: "kubernetes"

- name: Update APT cache after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install Kubernetes components (kubelet, kubeadm, kubectl)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold kubelet, kubeadm, and kubectl packages
  command: apt-mark hold kubelet kubeadm kubectl


- name: Disable swap
  command: swapoff -a

- name: Create /etc/modules-load.d/k8s.conf with required modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load overlay module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Create /etc/sysctl.d/k8s.conf with required kernel parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    mode: '0644'

- name: Apply sysctl parameters
  command: sysctl --system

- name: Reload sysctl configuration
  command: sysctl -p