---

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - socat
    state: present

- name: Ensure directory for apt keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Check if Kubernetes apt keyring exists
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: keyring_status

- name: Download and install Kubernetes apt keyring 
  shell: | 
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: not keyring_status.stat.exists

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: "kubernetes"

- name: Update APT cache after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install Kubernetes components (kubelet, kubeadm, kubectl)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold kubelet, kubeadm, and kubectl packages
  command: apt-mark hold kubelet kubeadm kubectl


- name: Disable swap
  command: swapoff -a

- name: Create /etc/modules-load.d/k8s.conf with required modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load overlay module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Create /etc/sysctl.d/k8s.conf with required kernel parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    mode: '0644'

- name: Apply sysctl parameters
  command: sysctl --system

- name: Reload sysctl configuration
  command: sysctl -p