---
- name: Install dependencies
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: Ensure /export/nfs/ directory exists
  ansible.builtin.file:
    path: /export/nfs/
    state: directory
    mode: '0755'

- name: Ensure /export/nfs/ <cluster network>(rw,sync,no_subtree_check,no_root_squash) is correctly written in /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "/export/nfs {{ cluster_network }}(rw,sync,no_subtree_check,no_root_squash)"
    regexp: '^/export/nfs'
    state: present
    insertafter: EOF

- name: reload nfs setting
  shell: exportfs -ra

- name: Initialize Kubernetes master node if not already initialized
  shell: >
    kubeadm init
    --kubernetes-version 1.30.2
    --pod-network-cidr={{ '192.168.0.0/16' if k8s_cni_plugin == 'calico' else '10.244.0.0/16' }}
    --control-plane-endpoint={{ control_plane_endpoint_ip }}
    --cri-socket=unix:///var/run/cri-dockerd.sock
    --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create a new token for worker nodes
  command: kubeadm token create --print-join-command
  register: kubeadm_worker_join_command_result

- name: Set worker join command as a fact
  set_fact:
    worker_join_command: "{{ kubeadm_worker_join_command_result.stdout }} --cri-socket=unix:///var/run/cri-dockerd.sock"

- name: Create a new token for additional master nodes
  command: kubeadm token create --print-join-command
  register: kubeadm_master_join_command_result

- name: Get certificate key for joining master nodes
  command: kubeadm init phase upload-certs --upload-certs
  register: kubeadm_certs_key_result

- name: Set additional master join command as a fact
  set_fact:
    additional_master_join_command: "{{ kubeadm_master_join_command_result.stdout }} --control-plane --certificate-key {{ kubeadm_certs_key_result.stdout_lines[-1] }} --cri-socket=unix:///var/run/cri-dockerd.sock"

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy admin.conf to kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes

- name: Change ownership of kube config
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Apply CNI network configuration
  block:
    - name: Apply Flannel network configuration
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: k8s_cni_plugin == 'flannel'
      register: cni_result

    - name: Apply Calico network configuration
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml
      when: k8s_cni_plugin == 'calico'
      register: cni_result
  - name: Check result of CNI deployment
    debug:
      var: cni_result

- name: Download and execute the Helm installation script
  shell: |
    curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash

- name: Add Helm repo for nfs-subdir-external-provisioner
  command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: Update Helm repo
  command: helm repo update

- name: Install nfs-subdir-external-provisioner
  command: helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ control_plane_endpoint_ip }} --set nfs.path=/export/nfs/
