---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  register: apt_install_result
  until: apt_install_result is succeeded
  retries: 5
  delay: 10

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install containerd
  apt:
    name:
      - containerd.io
    state: present
    update_cache: yes

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Remove existing containerd config.toml to force regeneration
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Generate containerd default config
  ansible.builtin.command: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Write containerd default config
  ansible.builtin.copy:
    content: "{{ containerd_default_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Set systemd as cgroup driver for containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Enable cri plugin for containerd by commenting out disabled_plugins
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*disabled_plugins\s*=.*"cri".*'
    replace: '# \g<0>'


- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

